language: bash

sudo: required
services:
  - docker

before_deploy:
  - docker build -t local/nativefier .
  - docker run -v "$TRAVIS_BUILD_DIR":/src local/nativefier --platform "linux" --icon /src/difm-logo.png --name "DI.FM" "https://www.di.fm" --honest --disable-dev-tools --single-instance --tray --internal-urls ".*" /src/
  - docker run -v "$TRAVIS_BUILD_DIR":/src local/nativefier --platform "windows" --icon /src/difm-logo.png --name "DI.FM" "https://www.di.fm" --honest --disable-dev-tools --single-instance --tray --internal-urls ".*" /src/
  - docker run -v "$TRAVIS_BUILD_DIR":/src local/nativefier --platform "mac" --icon /src/difm-logo.png --name "DI.FM" "https://www.di.fm" --honest --disable-dev-tools --single-instance --tray --internal-urls ".*" /src/
  - sudo chown -R travis:travis $TRAVIS_BUILD_DIR
  - for d in */ ; do base=$(basename "$d") ; cd "$base" ; zip -r "$base" * ; mv "${base}.zip" .. ; cd .. ; done;

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_KEY
  file:
    - "di-fm-win32-x64.zip"
    - "di-fm-darwin-x64.zip"
    - "di-fm-linux-x64.zip"
  skip_cleanup: true
  on:
    branch: master
    tags: true
